apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-{{.Values.Service.Name}} #my-service
spec:
  type: NodePort
  selector:
    app: api-server
  ports:
    - port: {{.Values.Service.ServicePort}} #3000
      targetPort: {{ .Values.Service.ContainerPort }} #3000
      nodePort: 30007