# cron-job.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: helloworld
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: busybox
            command: ["echo", "Hello Kubernetes!!!"]
          restartPolicy: Never
