apiVersion: v1
kind: Service
metadata:
  name: stateful-service
  labels:
    app: server
spec:
  ports:
  - port: 3000
  clusterIP: none
  selector:
    app: server

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: server
  serviceName: "statefull-service"
  replicas: 3
  template:
    metadata:
      labels:
        app: server
    spec:
      imagePullSecrets:
        - name: regsec
      containers:
      - name: server
        image: ishtiaq99/go-api-server:latest
        ports:
        - containerPort: 3000