apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: server
  serviceName: "statefull-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: ishtiaq99/go-api-server:latest
        ports:
        - containerPort: 3000