apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  volumes:
  # set volumes at the Pod level, then mount them into containers inside that Pod
  - name: demo
    configMap:
      # Provide the name of the ConfigMap to mount.
      name: demo-config
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
    volumeMounts:
    - name: demo # should be same as the name of volume
      mountPath: /mydata
