# temp-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
    name: helloworld
spec:
    activeDeadlineSeconds: 10
    template:
        spec:
            containers:
            - name: busybox
              image: busybox
              command: ["sleep", "30"]
            restartPolicy: Never
    backoffLimit: 4
